### ISSUE TITLE
Support for other formats

### ISSUE THREAD

**Issue by alexdevteam** [capo-devs/capo#16]
Support for common formats such as MP3, FLAC and OGG.

- [x] WAV
  - [x] dr_wav
  - [ ] custom?
- [x] MP3
  - [x] dr_mp3
- [x] FLAC
  - [x] dr_flac
- [ ] #21

**Comment by alexdevteam** [comment]
dr_flac supposedly supports OGG or something similar but I can't figure what/how to get it working. Maybe it needs to be OGG contained within FLAC, if that is even a thing?

**Comment by karnkaul** [comment]
Perhaps `dr_flac` supports `.ogg` too? It only returns decoded data, so the underlying format doesn't need to be a 1-1 mapping as such.

**Comment by alexdevteam** [comment]
I tried loading an ogg file already but it just fails

**Comment by karnkaul** [comment]
https://xiph.org/flac/faq.html#general__native_vs_ogg
Here's some interesting info I found on the topic

**Comment by alexdevteam** [comment]
I'll need to look further into it
