### ISSUE TITLE
OGG support

### ISSUE THREAD

**Issue by alexdevteam** [capo-devs/capo#21]

**Comment by alexdevteam** [comment]
Need to experiment with this; even if dr_flac does support it, there is something wrong somewhere preventing it from loading any ogg data

**Comment by alexdevteam** [comment]
Alright, dr_flac only supports FLAC and FLAC within OGG containers, not the other way around. Sad, we'll need to find another solution

**Comment by karnkaul** [comment]
My position is that it's not required. The MVP was WAV only, we also added FLAC and MP3, that's more than sufficient.

**Comment by alexdevteam** [comment]
Ok
