### ISSUE TITLE
Buffer/source lifetime handling

### ISSUE THREAD

**Issue by alexdevteam** [capo-devs/capo#4]
How to handle buffer/source lifetime: RAII wrappers or raw `ALuint`?

**Comment by karnkaul** [comment]
Discovered more constraints: all bound sources must first be unbound from a buffer before it can be deleted. There's some state management and tracking of bindings that's warranted.

**Comment by alexdevteam** [comment]
Maybe a refcounted source is a good idea then.

**Comment by karnkaul** [comment]
Perhaps, but not necessarily; eg, `Instance` could maintain mappings and dispose of resources correctly, keeping resource handles dumb (not RAII).

**Comment by alexdevteam** [comment]
Sounds good, could do something like `instance.delete(source)`. Keeping sources dumb seems like a good idea, keeps structs small and results on a more data oriented API.

**Comment by alexdevteam** [comment]
I'd prefer an opaque handle rather than a raw integer though. Doesn't make much sense to treat it as a primitive type.
