### ISSUE TITLE
Buffer streaming design

### ISSUE THREAD

**Issue by alexdevteam** [capo-devs/capo#6]
How to best handle streaming buffers (can assume single source here).

**Comment by karnkaul** [comment]
I've been thinking about this a bit. We need three aspects: 
- `N` OpenAL buffers of `S` size each attached to a source
- `M` CPU side buffers of the same size (all the parts, completing the audio data)
- one polling thread that performs buffer swaps every `t` seconds

The tricky part is finding a good balance for all these values, such that (a) we don't risk OOM on OpenAL, (b) playback is seamless, (c) polling overhead is minimal.

**Comment by alexdevteam** [comment]
This is already handled by OpenAL. On page 59 of the OpenAL's programmers guide
![Screenshot_20210926_212436](https://user-images.githubusercontent.com/16354904/134821416-57cbeafc-9aae-449b-bee4-f799c1138f91.png)
Sorry for not mentioning earlier, thought you already knew.
We just need to queue buffers when appropiate (maybe queue all of them while reading from data on a separate thread), swaps are not required.

**Comment by karnkaul** [comment]
Yeah I'd checked that out, the OpenAL buffer queue is internally managed. Problem is:
1. We can't create as many OpenAL buffers as there are pieces in the split music: OpenAL might go OOM; so the number and size of these buffers needs to be fixed per Music instance (well, ideally global limits but eff that).
2. The thread needs to poll at a reasonable interval such that it neither causes much overhead (too much polling), nor causes skips in playback (too little polling).
3. Finally, there needs to be either a file that's streamed for subsequent buffer gen, or a full massive PCM that will be split into `N` sub-PCMs, each of which will be sequentially bound to the source buffer queue.

**Comment by alexdevteam** [comment]
If we do the split manually aren't we just better off using a non-streaming sound source? In your case for the streaming source to make sense the engine would need to support asset streaming

**Comment by karnkaul** [comment]
There's probably a disconnect here. Streaming from an OpenAL point of view means but populating the entire song at once, but instead splitting it into parts. A 3 min piece will be about 30MB uncompressed, so we run the risk of exceeding audio device memory budget if we preload all such long pieces instead of streaming them.

To be clear, there's no streaming involved at the CPU / asset level - the entire file will be provided by the engine as a bunch of bytes (but that lives in RAM, so it's not an issue).

**Comment by karnkaul** [comment]
**Notes for self**

- [ ] Test file streaming
- [ ] Test memory streaming
- [ ] Decide on approach:
  - Upgrade `Source` to also support binding to `Music` (name TBD)
    - Might complicate instance mappings if the code paths aren't identical
  - Let `Music` be RAII, own its `Source`, etc: "on top" of instance
